In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd
import csv
import random
import math
import operator
from numpy import linalg as LA
import sys
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn import linear_model

In [2]:
df = pd.read_csv('AdmissionDataset/data.csv')
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0         242        317          103                  2  2.5   2.0  8.15   
1         334        319          108                  3  3.0   3.5  8.54   
2           4        322          110                  3  3.5   2.5  8.67   
3          45        326          113                  5  4.5   4.0  9.40   
4         232        319          106                  3  3.5   2.5  8.33   

   Research  Chance of Admit   
0         0              0.65  
1         1              0.71  
2         1              0.80  
3         1              0.91  
4         1              0.74

In [3]:
def MSE(theta,bias,X,Y,l):
    temp=np.dot(X,theta)
    Htheta=temp+bias
    t1=np.sum((Htheta-Y)**2)
    return (0.5/len(X))*(t1)

In [4]:
from sklearn.model_selection import train_test_split  
train,test = train_test_split(df, test_size=0.2)
train_y = train['Chance of Admit ']
train = train.drop('Serial No.',axis=1)
train = train.drop('Chance of Admit ',axis=1)
test_y = test['Chance of Admit ']
test = test.drop('Serial No.',axis=1)
test = test.drop('Chance of Admit ',axis=1)

In [5]:
xtrain=np.array(train)
xtrain=(xtrain-xtrain.mean(axis=0))/xtrain.std(axis=0)
print(xtrain.shape)
ytrain=np.array(train_y)
ytrain=ytrain.reshape((len(ytrain),1))
print(ytrain.shape)
xtest=np.array(test)
xtest=(xtest-xtest.mean(axis=0))/xtest.std(axis=0)
ytest=np.array(test_y)
ytest=ytest.reshape((len(ytest),1))
ytest.shape

(360, 7)
(360, 1)


(90, 1)

In [6]:
def cost_func_ridge(theta,bias,X,Y,l):
    temp=np.dot(X,theta)
    Htheta=temp+bias
    t1=np.sum((Htheta-Y)**2)
    t2=l*np.sum(theta**2)
    return (0.5/len(X))*(t1+t2)

In [7]:
def grad_des_ridge(X,Y,lr,epochs,l):
    theta=np.zeros((X.shape[1],1))
    bias=0
    for e in range(epochs):
        temp=np.dot(X,theta)
        Htheta=temp+bias
        db=np.sum(Htheta-Y)
        dtheta=np.dot(X.T,(Htheta-Y))
        ridge_diff=dtheta+l*theta
        bias=bias-(lr/len(X)*db)
        theta=theta-(lr/len(X)*ridge_diff)
    return theta,bias

In [8]:
def cost_func_lasso(theta,bias,X,Y,l):
    temp=np.dot(X,theta)
    Htheta=temp+bias
    t1=np.sum((Htheta-Y)**2)
    t2=l*np.sum(np.abs(theta))
    return (0.5/len(X))*(t1+t2)

In [9]:
def grad_des_lasso(X,Y,lr,epochs,l):
    theta=np.zeros((X.shape[1],1))
    bias=0
    for e in range(epochs):
        temp=np.dot(X,theta)
        Htheta=temp+bias
        db=np.sum(Htheta-Y)
        dtheta=np.dot(X.T,(Htheta-Y))
        lasso_diff=dtheta+l*np.sign(theta)
        bias=bias-(lr/len(X)*db)
        theta=theta-(lr/len(X)*lasso_diff)
    return theta,bias

In [10]:
theta,bias=grad_des_ridge(xtrain,ytrain,0.1,1000,20)
errval1=MSE(theta,bias,xtest,ytest,20)
errval1

0.00183721554303727

In [19]:
theta1,bias1=grad_des_lasso(xtrain,ytrain,0.1,1000,0.5)
errval2=MSE(theta,bias,xtest,ytest,0.5)

### Weights in Ridge Regression:-

In [20]:
theta

array([[0.02446183],
       [0.01790003],
       [0.00505994],
       [0.00504016],
       [0.01588339],
       [0.06082014],
       [0.0129924 ]])

### Weights in Lasso Regression:-

In [21]:
theta1

array([[0.02180841],
       [0.01461248],
       [0.00262963],
       [0.00208403],
       [0.01491075],
       [0.07232452],
       [0.01235453]])

In [22]:
diff=np.subtract(theta,theta1)

### Difference in both weights:-

In [23]:
diff

array([[ 0.00265341],
       [ 0.00328755],
       [ 0.00243031],
       [ 0.00295613],
       [ 0.00097264],
       [-0.01150438],
       [ 0.00063787]])

#### So , both weights are nearly equal on respective best lambdas for Lasso and Ridge.